name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'poetry'
    - run: poetry install
    - run: poetry run ruff check .
    - run: poetry run black aisploit --check
    - run: poetry run mypy aisploit
    - run: poetry run pytest